-- 日次クォータ判定用のインデックス（4.3 / 確定25 / #23）。
--
-- **列は足さない。** `generations` は 0001 で 5.1 のとおり作られており、判定に要る
-- `user_id` も `created_at` も揃っている。本 migration が足すのはインデックス 1 本だけである。
--
-- **0003 がこの索引を #23 へ申し送っている。** あちらは月次集計用の
-- `generations(created_at)` を張り、「利用者別の索引は張らない。日次クォータ
-- （確定25 / 1 人 1 日 12 回）の判定は #23 の範囲で、そちらが `(user_id, created_at)` を
-- 要する。**要る側が張る**」と書いた。**その問い合わせが来た。**
-- `src/quota.ts` の `dailyCallCount` が
--
--   select count(*) from generations
--    where user_id = ? and created_at >= ? and created_at < ?
--
-- を引く。これは 3.3-2 の判定なので、**生成のたびに 1 回走る。**
--
-- **0003 の `(created_at)` では代われない。** あちらの先頭列は `created_at` なので、
-- この問い合わせは「当月の全利用者の行」を読んでから `user_id` で捨てることになる。
-- **D1 は読み取りも従量である**（3.6）。1 人あたり 1 日 12 回という枠に対して、
-- 招待者 30 人ぶんの当日の行を毎回読むのは、枠の判定 1 回の代償として釣り合わない。
--
-- **`(user_id, created_at)` の順にする。** 判定は `user_id` の等値で絞ってから
-- `created_at` の範囲を取るため、この順でのみ範囲走査が 1 人・1 日ぶんに収まる。
-- 逆順（`(created_at, user_id)`）は 0003 の索引とほぼ同じ効きしか持たない。
--
-- **`succeeded` は含めない。** 日次クォータが数えるのは「費用の出る LLM 呼び出し回数」
-- （確定25）であって成功回数ではない。列を足すと、成否で絞る実装を誘発する。
CREATE INDEX generations_user_id_created_at_idx ON generations(user_id, created_at);
