#!/usr/bin/env bash
# check-worker-types.sh — worker-configuration.d.ts が wrangler.toml と一致していることの機械照合。
#
# 位置づけ:
#   worker-configuration.d.ts は `wrangler types` が wrangler.toml から生成する
#   「バインディングの一覧」である。14,000 行超の生成物なので追跡はしない
#   （共通規範「再生成できる大容量の生成物はコミットしない」）。`npm ci` の
#   prepare が生成する。
#
#   追跡していなくても古くなる経路は残る: wrangler.toml を変えたのに再生成しないと、
#   手元のファイルは古い一覧のまま型検査を通してしまう（shared-ai-rules 12 章
#   「一覧の複製は機械照合で担保する」）。生成し直した結果と突き合わせ、差があれば落とす。
#
#   これは「再生成したか」ではなく「一致しているか」を検査する。空更新では通らない。
#
#   副次的にもう 1 つ効く: wrangler は既定でリポジトリ直下の .env をシークレットとして
#   読み込み、その結果が生成物へ現れる。この照合を通すには .env の読み込みを止めた
#   状態で生成する必要があり、混入が起きれば差分として表面化する。
#
# 終了コード:
#   0 = WORKER_TYPES_PASS
#   1 = WORKER_TYPES_FAIL（不一致、または検査が成立しなかった）
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$(dirname "$HERE")"

CURRENT="worker-configuration.d.ts"

fail() {
  printf '[worker-types] %s\n' "$1" >&2
  echo "WORKER_TYPES_FAIL"
  exit 1
}

[[ -f wrangler.toml ]] || fail "wrangler.toml がありません。照合の対象がありません。"
[[ -f "$CURRENT" ]] || fail "$CURRENT がありません。'npm ci'（prepare が生成する）か 'npm run types' を実行してください。"

command -v npx >/dev/null 2>&1 || fail "npx が見つかりません。Node.js を導入してください。"
[[ -d node_modules/wrangler ]] || fail "node_modules/wrangler がありません。'npm ci' を先に実行してください。"

# 生成先はリポジトリ直下に置く。`wrangler types` の出力には、出力先から見た
# 相対パス（`mainModule: typeof import("./src/index")`）が埋め込まれるため、
# 別ディレクトリへ生成すると、宣言が同じでも中身が変わって照合が成立しない。
GENERATED=".worker-configuration.check.d.ts"
LOG=""
# trap から呼ぶため、静的解析からは呼び出しが見えない。
# shellcheck disable=SC2329
cleanup() {
  rm -f -- "$GENERATED"
  [[ -n "$LOG" ]] && rm -rf -- "$LOG"
  return 0
}
trap cleanup EXIT
LOG="$(mktemp -d "${TMPDIR:-/tmp}/worker-types.XXXXXX")" || fail "一時ディレクトリを作成できませんでした。"

# .env の読み込みを明示的に止めて生成する。既定（true）のままだと、リポジトリ直下の
# .env のキーが生成物へ混ざり、環境ごとに結果が変わって照合が成立しない。
if ! CLOUDFLARE_LOAD_DEV_VARS_FROM_DOT_ENV=false \
     npx wrangler types "$GENERATED" >"$LOG/stdout.log" 2>&1; then
  sed 's/^/    /' "$LOG/stdout.log" >&2
  fail "wrangler types の実行に失敗しました。"
fi

[[ -s "$GENERATED" ]] || fail "wrangler types が空の出力を返しました。検査が成立しません。"

# 生成コマンド行だけは出力先ファイル名を含むため、両側から落として比較する。
# ここを残すと、ファイル名が違うという理由だけで常に不一致になる。
# 残りの全行（バインディングの一覧とランタイム型）は完全一致を要求する。
strip_header() {
  grep -v '^// Generated by Wrangler by running' "$1"
}

if ! diff -u <(strip_header "$CURRENT") <(strip_header "$GENERATED") >"$LOG/diff.txt"; then
  printf '[worker-types] %s が wrangler.toml の宣言と一致しません。\n' "$CURRENT" >&2
  sed 's/^/    /' "$LOG/diff.txt" >&2
  printf '[worker-types] 対処: npm run types を実行して生成し直してください。\n' >&2
  fail "不一致を検出しました。"
fi

echo "WORKER_TYPES_PASS"
exit 0
