/**
 * Ebitengine のキーの表（仕様 3.9.5 / #493）。**このファイルは生成物である。手で書き換えない。**
 *
 * - 正本: `github.com/hajimehoshi/ebiten/v2@v2.9.9` の `keys.go`（`Key*` 定数）と `internal/ui/keys_js.go`（`uiKeyToJSCode`）
 * - 生成: `node scripts/ebiten-keys-table.mjs --write`
 * - 照合: `node scripts/ebiten-keys-table.mjs --check`（`scripts/acceptance.sh` が呼ぶ）
 *
 * 左右の区別の無い `Alt` / `Control` / `Meta` / `Shift` は左へ写し、`KeyMax` は捨てる（3.9.5 の 2）。
 * 読むのは `src/input-keys.ts` だけにする。
 */

/** 生成に使った Ebitengine の版（`docker/isolated-build/template/go.mod`）。 */
export const EBITEN_MODULE_VERSION = 'v2.9.9';

/** 生成に使ったモジュールの h1（`docker/isolated-build/template/go.sum`）。 */
export const EBITEN_MODULE_SUM = 'h1:JdDag6Ndj12iD4lxQGG8kbsrh7ssj4Sbzth6r929H/M=';

/** `ebiten.Key<名前>` の `<名前>` → `KeyboardEvent.code`。 */
export const EBITEN_KEY_CODES: Readonly<Record<string, string>> = {
  '0': 'Digit0',
  '1': 'Digit1',
  '2': 'Digit2',
  '3': 'Digit3',
  '4': 'Digit4',
  '5': 'Digit5',
  '6': 'Digit6',
  '7': 'Digit7',
  '8': 'Digit8',
  '9': 'Digit9',
  'A': 'KeyA',
  'Alt': 'AltLeft',
  'AltLeft': 'AltLeft',
  'AltRight': 'AltRight',
  'Apostrophe': 'Quote',
  'ArrowDown': 'ArrowDown',
  'ArrowLeft': 'ArrowLeft',
  'ArrowRight': 'ArrowRight',
  'ArrowUp': 'ArrowUp',
  'B': 'KeyB',
  'Backquote': 'Backquote',
  'Backslash': 'Backslash',
  'Backspace': 'Backspace',
  'BracketLeft': 'BracketLeft',
  'BracketRight': 'BracketRight',
  'C': 'KeyC',
  'CapsLock': 'CapsLock',
  'Comma': 'Comma',
  'ContextMenu': 'ContextMenu',
  'Control': 'ControlLeft',
  'ControlLeft': 'ControlLeft',
  'ControlRight': 'ControlRight',
  'D': 'KeyD',
  'Delete': 'Delete',
  'Digit0': 'Digit0',
  'Digit1': 'Digit1',
  'Digit2': 'Digit2',
  'Digit3': 'Digit3',
  'Digit4': 'Digit4',
  'Digit5': 'Digit5',
  'Digit6': 'Digit6',
  'Digit7': 'Digit7',
  'Digit8': 'Digit8',
  'Digit9': 'Digit9',
  'Down': 'ArrowDown',
  'E': 'KeyE',
  'End': 'End',
  'Enter': 'Enter',
  'Equal': 'Equal',
  'Escape': 'Escape',
  'F': 'KeyF',
  'F1': 'F1',
  'F10': 'F10',
  'F11': 'F11',
  'F12': 'F12',
  'F13': 'F13',
  'F14': 'F14',
  'F15': 'F15',
  'F16': 'F16',
  'F17': 'F17',
  'F18': 'F18',
  'F19': 'F19',
  'F2': 'F2',
  'F20': 'F20',
  'F21': 'F21',
  'F22': 'F22',
  'F23': 'F23',
  'F24': 'F24',
  'F3': 'F3',
  'F4': 'F4',
  'F5': 'F5',
  'F6': 'F6',
  'F7': 'F7',
  'F8': 'F8',
  'F9': 'F9',
  'G': 'KeyG',
  'GraveAccent': 'Backquote',
  'H': 'KeyH',
  'Home': 'Home',
  'I': 'KeyI',
  'Insert': 'Insert',
  'IntlBackslash': 'IntlBackslash',
  'J': 'KeyJ',
  'K': 'KeyK',
  'KP0': 'Numpad0',
  'KP1': 'Numpad1',
  'KP2': 'Numpad2',
  'KP3': 'Numpad3',
  'KP4': 'Numpad4',
  'KP5': 'Numpad5',
  'KP6': 'Numpad6',
  'KP7': 'Numpad7',
  'KP8': 'Numpad8',
  'KP9': 'Numpad9',
  'KPAdd': 'NumpadAdd',
  'KPDecimal': 'NumpadDecimal',
  'KPDivide': 'NumpadDivide',
  'KPEnter': 'NumpadEnter',
  'KPEqual': 'NumpadEqual',
  'KPMultiply': 'NumpadMultiply',
  'KPSubtract': 'NumpadSubtract',
  'L': 'KeyL',
  'Left': 'ArrowLeft',
  'LeftBracket': 'BracketLeft',
  'M': 'KeyM',
  'Menu': 'ContextMenu',
  'Meta': 'MetaLeft',
  'MetaLeft': 'MetaLeft',
  'MetaRight': 'MetaRight',
  'Minus': 'Minus',
  'N': 'KeyN',
  'NumLock': 'NumLock',
  'Numpad0': 'Numpad0',
  'Numpad1': 'Numpad1',
  'Numpad2': 'Numpad2',
  'Numpad3': 'Numpad3',
  'Numpad4': 'Numpad4',
  'Numpad5': 'Numpad5',
  'Numpad6': 'Numpad6',
  'Numpad7': 'Numpad7',
  'Numpad8': 'Numpad8',
  'Numpad9': 'Numpad9',
  'NumpadAdd': 'NumpadAdd',
  'NumpadDecimal': 'NumpadDecimal',
  'NumpadDivide': 'NumpadDivide',
  'NumpadEnter': 'NumpadEnter',
  'NumpadEqual': 'NumpadEqual',
  'NumpadMultiply': 'NumpadMultiply',
  'NumpadSubtract': 'NumpadSubtract',
  'O': 'KeyO',
  'P': 'KeyP',
  'PageDown': 'PageDown',
  'PageUp': 'PageUp',
  'Pause': 'Pause',
  'Period': 'Period',
  'PrintScreen': 'PrintScreen',
  'Q': 'KeyQ',
  'Quote': 'Quote',
  'R': 'KeyR',
  'Right': 'ArrowRight',
  'RightBracket': 'BracketRight',
  'S': 'KeyS',
  'ScrollLock': 'ScrollLock',
  'Semicolon': 'Semicolon',
  'Shift': 'ShiftLeft',
  'ShiftLeft': 'ShiftLeft',
  'ShiftRight': 'ShiftRight',
  'Slash': 'Slash',
  'Space': 'Space',
  'T': 'KeyT',
  'Tab': 'Tab',
  'U': 'KeyU',
  'Up': 'ArrowUp',
  'V': 'KeyV',
  'W': 'KeyW',
  'X': 'KeyX',
  'Y': 'KeyY',
  'Z': 'KeyZ',
};

/** 上の表が写す `code` の集合（重複を除き、昇順）。 */
export const EBITEN_KEY_CODE_LIST: readonly string[] = [
  'AltLeft',
  'AltRight',
  'ArrowDown',
  'ArrowLeft',
  'ArrowRight',
  'ArrowUp',
  'Backquote',
  'Backslash',
  'Backspace',
  'BracketLeft',
  'BracketRight',
  'CapsLock',
  'Comma',
  'ContextMenu',
  'ControlLeft',
  'ControlRight',
  'Delete',
  'Digit0',
  'Digit1',
  'Digit2',
  'Digit3',
  'Digit4',
  'Digit5',
  'Digit6',
  'Digit7',
  'Digit8',
  'Digit9',
  'End',
  'Enter',
  'Equal',
  'Escape',
  'F1',
  'F10',
  'F11',
  'F12',
  'F13',
  'F14',
  'F15',
  'F16',
  'F17',
  'F18',
  'F19',
  'F2',
  'F20',
  'F21',
  'F22',
  'F23',
  'F24',
  'F3',
  'F4',
  'F5',
  'F6',
  'F7',
  'F8',
  'F9',
  'Home',
  'Insert',
  'IntlBackslash',
  'KeyA',
  'KeyB',
  'KeyC',
  'KeyD',
  'KeyE',
  'KeyF',
  'KeyG',
  'KeyH',
  'KeyI',
  'KeyJ',
  'KeyK',
  'KeyL',
  'KeyM',
  'KeyN',
  'KeyO',
  'KeyP',
  'KeyQ',
  'KeyR',
  'KeyS',
  'KeyT',
  'KeyU',
  'KeyV',
  'KeyW',
  'KeyX',
  'KeyY',
  'KeyZ',
  'MetaLeft',
  'MetaRight',
  'Minus',
  'NumLock',
  'Numpad0',
  'Numpad1',
  'Numpad2',
  'Numpad3',
  'Numpad4',
  'Numpad5',
  'Numpad6',
  'Numpad7',
  'Numpad8',
  'Numpad9',
  'NumpadAdd',
  'NumpadDecimal',
  'NumpadDivide',
  'NumpadEnter',
  'NumpadEqual',
  'NumpadMultiply',
  'NumpadSubtract',
  'PageDown',
  'PageUp',
  'Pause',
  'Period',
  'PrintScreen',
  'Quote',
  'ScrollLock',
  'Semicolon',
  'ShiftLeft',
  'ShiftRight',
  'Slash',
  'Space',
  'Tab',
];
